import logging
from app.models.asset import MonetizationModel, AssetType
from app.config import settings

logger = logging.getLogger(__name__)


def inject_affiliate_links(html: str, keyword: str) -> str:
    """Inject Amazon Associates search link into CTA buttons."""
    tag = settings.AMAZON_ASSOCIATE_TAG
    search_query = keyword.replace(" ", "+")
    affiliate_url = (
        f"https://www.amazon.com/s?k={search_query}&tag={tag}"
    )
    # Replace placeholder affiliate URLs generated by Claude
    html = html.replace("https://amazon.com/AFFILIATE_LINK", affiliate_url)
    html = html.replace("YOUR_AFFILIATE_LINK", affiliate_url)

    # Inject affiliate script snippet before </body> if not already present
    if "amazon-adsystem" not in html and tag != "arostag-20":
        snippet = f"""
<script>
  document.querySelectorAll('a[data-affiliate]').forEach(a => {{
    a.href = '{affiliate_url}';
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
  }});
</script>"""
        html = html.replace("</body>", f"{snippet}\n</body>")

    return html


def inject_adsense(html: str, adsense_client: str = "ca-pub-XXXXXXXXXXXXXXXX") -> str:
    """Inject Google AdSense script into <head>."""
    adsense_script = f"""
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={adsense_client}"
  crossorigin="anonymous"></script>"""
    html = html.replace("</head>", f"{adsense_script}\n</head>", 1)
    return html


def inject_stripe_button(html: str, price_id: str) -> str:
    """Inject Stripe payment button (uses publishable key from meta tag)."""
    stripe_js = f"""
<script src="https://js.stripe.com/v3/"></script>
<script>
  const stripe = Stripe(document.querySelector('meta[name="stripe-pk"]')?.content || '');
  document.querySelectorAll('[data-stripe-checkout]').forEach(btn => {{
    btn.addEventListener('click', async () => {{
      await stripe.redirectToCheckout({{ lineItems: [{{price: '{price_id}', quantity: 1}}], mode: 'payment', successUrl: window.location.href + '?success=1', cancelUrl: window.location.href }});
    }});
  }});
</script>"""
    html = html.replace("</body>", f"{stripe_js}\n</body>", 1)
    return html


def inject_tracking_pixel(html: str, asset_id: int, api_base: str = "") -> str:
    if not api_base:
        from app.config import settings
        api_base = settings.AROS_API_URL
    """Inject a lightweight tracking pixel that reports page visits to the analytics API."""
    pixel = f"""
<script>
  (function(){{
    var _aid={asset_id};
    fetch('{api_base}/api/analytics/'+_aid+'/track',{{
      method:'POST',
      headers:{{'Content-Type':'application/json'}},
      body:JSON.stringify({{visits:1}}),
      keepalive:true
    }}).catch(function(){{}});
  }})();
</script>"""
    return html.replace("</body>", f"{pixel}\n</body>", 1)


async def attach_monetization(
    html: str, keyword: str, model: MonetizationModel, asset_type: AssetType,
    asset_id: int | None = None, api_base: str = "http://localhost:8000",
) -> str:
    """Apply monetization strategy to HTML content and inject tracking pixel."""
    logger.info(f"[Monetization] Aplicando modelo: {model.value}")

    if model == MonetizationModel.AFFILIATES:
        html = inject_affiliate_links(html, keyword)

    elif model == MonetizationModel.ADS:
        html = inject_adsense(html)

    elif model == MonetizationModel.ECOMMERCE and settings.STRIPE_SECRET_KEY:
        html = inject_stripe_button(html, price_id="price_PLACEHOLDER")

    if asset_id is not None:
        html = inject_tracking_pixel(html, asset_id, api_base)
        logger.info(f"[Monetization] Tracking pixel inyectado para asset #{asset_id}")

    logger.info(f"[Monetization] Inyección completada para modelo: {model.value}")
    return html
